spring:
  datasource:
    master:
      jdbc-url: ${MASTER_DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
    slave:
      jdbc-url: ${SLAVE_DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
jwt:
  secret: ${JWT_SECRET}
  exp: ${JWT_EXP}

